### ISSUE TITLE
Are patches required in QT 4.6.0 sources for mdiswiz? 

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13Y008-90#1]
For the mdiswiz Windows executable, some patches are required within the QT 4.6.0 sources. These patches are stored in our old MCVS.
Because I never built mdiswiz under Linux, I don't know if the patches in the QT sources are necessary for Linux too. I found no MEN patches for QT stored at GitHub and the patches itself looks like they apply to Windows only. But to be sure:
Do you use any patches or the original QT 4.6.0 sources to build the mdiswiz under Linux?

I need this information because of the mdiswiz licensing.

**Comment by mlassota** [comment]
> Do you use any patches or the original QT 4.6.0 sources to build the mdiswiz under Linux?

We use just the original Qt 4.6.0 sources to build mdiswiz under Linux.
